spec_name: "guesswhat"  # Replace with actual game spec name

teacher:
  model_name: "Unsloth-Llama-3-8B"   # Replace with actual model name
  
learner:
  model_name: "Unsloth-Llama-3-8B"   # Replace with actual model name
