spec_name: "privateshared"  # Replace with actual game spec name

learner:
  model_name: "Meta-Llama-3.1-8B-Instruct"   # Replace with actual model name
  max_tokens: 350
  temperature: 1.0
  name: "Player 1" # Answerer

  
teacher:
  model_name: "gpt-4o-mini-2024-07-18"   # Replace with actual model name
  max_tokens: 350
  temperature: 1.0
  name: "Player 2" # Questioner