spec_name: "referencegame"  # Replace with actual game spec name

learner:
  model_name: "Wordle-curr-taboo"   # Replace with actual model name
  max_tokens: 350
  temperature: 1.0
  name: "Player 2" # instruction follower

  
teacher:
  model_name: "gpt-4o-mini-2024-07-18"   # Replace with actual model name
  max_tokens: 350
  temperature: 1.0
  name: "Player 1" # instruction giver