rollout_steps: 128
rollout_iterations: 1000
eval_frequency: 50
eval_episodes: 2
critic_epochs: 50
actor_epochs: 3
max_grad_norm: 0.5
tau: 0.005
batch_size: 1
num_workers: 4
gamma: 0.99
eval_instances: "test_instances.json"
eval_rollout_steps: 128