rollout_steps: 256
rollout_iterations: 60
eval_frequency: 5
eval_episodes: 5
critic_epochs: 5
actor_epochs: 2
max_grad_norm: 0.5
tau: 0.9
batch_size: 8
num_workers: 1
gamma: 0.98
eval_instances: "test_instances.json"
eval_rollout_steps: 256
warmup_iters: 1
scale_reward: False
scaling_factor: 100.00
