rollout_steps: 50
rollout_iterations: 40
eval_frequency: 5
eval_episodes: 5
critic_epochs: 8
actor_epochs: 2
max_grad_norm: 0.5
tau: 0.1
critic_batch_size: 128  # Can be larger since critic is smaller
actor_batch_size: 8    # May need to be smaller due to LoRA model size
num_workers: 1
gamma: 0.97
eval_instances: "test_instances.json"
eval_rollout_steps: 10
warmup_iters: 3
scale_reward: False
scaling_factor: 100.00
is_replay_buffer: True
step_size: 256