rollout_steps: 60
rollout_iterations: 100
eval_frequency: 5
eval_episodes: 5
critic_epochs: 6
actor_epochs: 3
max_grad_norm: 0.5
tau: 0.9
batch_size: 16
num_workers: 1
gamma: 0.98
eval_instances: "test_instances.json"
eval_rollout_steps: 18
warmup_iters: 2
scale_reward: False
scaling_factor: 100.00
is_replay_buffer: True
