rollout_steps: 256
rollout_iterations: 20
eval_frequency: 5
eval_episodes: 5
critic_epochs: 10
actor_epochs: 3
max_grad_norm: 0.5
tau: 0.9
batch_size: 1
num_workers: 1
gamma: 0.98
eval_instances: "test_instances.json"
eval_rollout_steps: 128
warmup_iters: 1
