rollout_steps: 256
rollout_iterations: 40
eval_frequency: 4
eval_episodes: 5
critic_epochs: 5
actor_epochs: 2
max_grad_norm: 0.5
tau: 0.9
batch_size: 16
num_workers: 1
gamma: 0.98
eval_instances: "test_instances.json"
eval_rollout_steps: 128
warmup_iters: 1
scale_reward: False
scaling_factor: 100.00
is_replay_buffer: True
