_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 11
                - 49
                - 50
                - 55
                - 71
                - 105
            "2":
                - 1
                - 11
                - 49
                - 50
                - 55
                - 71
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.11
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
device:
    value: cuda
game:
    value: '{''spec_name'': ''guesswhat'', ''teacher'': {''model_name'': ''Unsloth-Llama-3-8B'', ''max_tokens'': 300, ''temperature'': 0.3}, ''learner'': {''model_name'': ''Unsloth-Llama-3-8B'', ''max_tokens'': 300, ''temperature'': 0.3}}'
loss:
    value: '{''actor'': {''_target_'': ''modelling.archer_critic.Reinforce''}, ''critic'': {''_target_'': ''modelling.archer_critic.TDLoss''}}'
model:
    value: '{''critic'': {''hidden_dims'': [512, 512], ''critic_lm'': ''FacebookAI/roberta-base''}}'
optimizer:
    value: '{''actor'': {''_target_'': ''torch.optim.Adam'', ''lr'': 1e-06, ''betas'': [0.9, 0.999]}, ''critic'': {''_target_'': ''torch.optim.Adam'', ''lr'': 2e-05, ''betas'': [0.9, 0.999]}}'
project_name:
    value: archer-rl
seed:
    value: 42
trainer:
    value: '{''rollout_steps'': 32, ''rollout_iterations'': 15, ''eval_frequency'': 5, ''eval_episodes'': 2, ''critic_epochs'': 10, ''actor_epochs'': 3, ''max_grad_norm'': 0.5, ''tau'': 0.005, ''batch_size'': 32, ''num_workers'': 4}'
