defaults:
  - trainer: default
  - optimizer: default
  - model: default
  - loss: default
  - game: default
  - _self_

project_name: archer-rl
run_name: "sparse_rewards_episode_reward_v1"
group: "Sparse Rewards"
seed: 42
device: cuda
