defaults:
  - trainer: default
  - optimizer: default
  - model: default
  - loss: default
  - game: wordle
  - lora: default
  - _self_

top_dir: "/scratch/usr/bbmdr998/thesis/playpen"
checkpoint_dir: "/scratch/usr/bbmdr998/thesis/checkpoints"
eval_results_dir: "/scratch/usr/bbmdr998/thesis/playpen_eval"
offline: True
project_name: archer-rl
run_name: "Wordle-exp-gen-2-cont"
group: "Wordle"
seed: 42
device: cuda
