defaults:
  - trainer: default
  - optimizer: default
  - model: default
  - loss: default
  - game: default
  - lora: default
  - _self_

project_name: archer-rl
run_name: "Dense E2 - Functional V1"
group: "Dense - E2"
seed: 42
device: cuda
