defaults:
  - trainer: default
  - optimizer: default
  - model: default
  - loss: default
  - game: wordle
  - lora: default
  - _self_

project_name: archer-rl
run_name: "GID-Wordle-DEBUG"
group: "Wordle"
seed: 42
device: cuda
